// <auto-generated />
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(FilmDataContext))]
    partial class FilmDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("FilmCollection.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.FilmData", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Director = "Michael Gracey",
                            Edited = "no",
                            Notes = "Mom's favorite movie",
                            Rating = "PG",
                            Title = "The Greatest Showman",
                            Year = 2017
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 2,
                            Director = "David Yates",
                            Edited = "yes",
                            Lent_To = "Older Brother",
                            Rating = "PG-13",
                            Title = "Harry Potter: The Deathly Hallows Pt. 2",
                            Year = 2011
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 3,
                            Director = "John Stevenson, Mark Osborne",
                            Edited = "no",
                            Rating = "PG",
                            Title = "Kung Fu Panda",
                            Year = 2008
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.FilmData", b =>
                {
                    b.HasOne("FilmCollection.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
